"""add product tryon_size_mm

Revision ID: b82f7a368e2f
Revises: 63eaab787445
Create Date: 2026-10-01 17:19:46.814101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82f7a368e2f'
down_revision: Union[str, None] = '63eaab787445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tryon_size_mm', sa.Numeric(precision=5, scale=1), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('tryon_size_mm')

    # ### end Alembic commands ###
