"""add candidate label

Revision ID: eef4b6aa7043
Revises: bdf10dc958fa
Create Date: 2026-10-05 22:24:02.141504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef4b6aa7043'
down_revision: Union[str, None] = 'bdf10dc958fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_candidates', schema=None) as batch_op:
        # server_default='' backfills existing rows so NOT NULL is satisfiable.
        batch_op.add_column(
            sa.Column('label', sa.String(length=40), nullable=False, server_default='')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_candidates', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
